### Good request
POST http://localhost:8000/vm/start

{
    "cpu_count": 12,
    "mem_size_gb": 100,
    "image": "debian:bookworm"
}

### Stop (change ID)
POST http://localhost:8000/vm/"put the id here"/stop

### CPU count too high
POST http://localhost:8000/vm/start

{
    "cpu_count": 400,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}